version: "3.3"
services:
  mlflow:
    container_name: mlflow
    build : 
      context: .
      args:
        ARTIFACT_ROOT: gs://krian-mai-krian-proj/mlflow-artifact-store
        SECRET_PATH: ./secret.json
        DB_URI: postgresql://admin:password@mlflow-db:5432/mlflow-tracking-server-db
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns/

  mlflow-db:
    container_name: mlflow-db
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=mlflow-tracking-server-db